---
title: "Projet SAE3.03"
author: "cedric"
date: '2023-09-15'
output: html_document
---

```{r}
i=read.csv("~/Téléchargements/route_intersection.csv")
i=read.csv("C:/Users/Cédric/Downloads/route_intersection.csv")
i$date=as.Date(i$date)

library(tidyverse)
#tendance globale entrée groupé I

I= i %>% 
    group_by(day = lubridate::floor_date(date, 'day')) %>%
    summarize(sum = sum(vehicule))
I #flux global

i[1,2]

for (j in 1:length(i[,2])){
  if (i[j,2] == "I1" ||   i[j,2] == "I2" || i[j,2] == "I3"){
    i[j,2] = "I"
  }
} 
I=i[i$intersection == "I",]
I = I %>% 
    group_by(day = lubridate::floor_date(date, 'day')) %>%
    summarize(sum = sum(vehicule))

I
plot.new()
plot(y=I$sum,x=I$day)
abline(v = as.numeric(as.Date("2017-01-01")), col = "red", lty = 2)


library(ggplot2)
ggplot(data = I, aes(x=day,y=sum))+
  geom_point()+
  geom_vline(xintercept =as.numeric(as.Date("2017-01-01")),color="red",linetype="dashed")+
  labs(x="Date",y="Nombre de véhicule")

#application moyenne mobile , regression expo

#serie des différences
I$diff = c(NA,diff(I$sum)) 
plot(y=I$diff,x= I$day)
abline(h=0) #executer dans terminal les 2 lignes plot et abline

#taux de croissance
I$tc=rep(NA,length(I$sum))
for (i in 2:length(I$sum)){
  I$tc[i]= I$sum[i]/I$sum[i-1]-1
}
plot(y=I$tc,x=I$day)

#moyenne mobile
library(zoo)
k=7
I$mm=c(rep(NA,k),rollmean(I$sum,k=2*k+1),rep(NA,k))
plot(y=I$mm,x=I$day)


#test de 1 à 20 (k) (moy mob)
k_values <- 1:20

par(mfrow = c(5, 4))  # Divise la fenêtre de tracé en 5 lignes et 4 colonnes

for (k in k_values) {
  # Calculer la moyenne mobile avec rollmean
  I$mm <- c(rep(NA, k), zoo::rollmean(I$sum, k = 2 * k + 1), rep(NA, k))
  
  # Tracer la courbe pour cette valeur de k
  plot(x = I$day, y = I$mm, type = "p", main = paste("k =", k), xlab = "Date", ylab = "Moyenne mobile")
}

#version ggplot2

k_values <- 1:20

plots <- list()


for (k in k_values) {

  I$mm <- c(rep(NA, k), zoo::rollmean(I$sum, k = 2 * k + 1), rep(NA, k))
  
 
  p <- ggplot(I, aes(x = day, y = mm)) +
    geom_point() +
    labs(title = paste("k =", k), x = "Date", y = "Moyenne mobile")
  
  plots[[k]] <- p
}
print(plots)

#choix k=3 ou k=10:20 bien lissé ... 

#anomalie (baisse forte) autour de 2017-01-01

par(mfrow = c(1,1)) #reinitialiser paramètre graphique

l=lm(I$sum~I$day)
summary(lm(I$sum~I$day))
l$coefficients
plot(y=I$sum,x=I$day)
x=seq(as.Date("2016-01-01"),as.Date("2017-07-01"),by="day")
y=-54594.606532+3.306*as.numeric(x)
y[1]

#tendance globale (simple modèle linéaire) execute les 2 lignes dans terminal pour afficher le graph dans  la fenêtre graphique
plot(y=I$sum,x=I$day)
lines(y~x)

#lissage exponentielle
#require("forecast")
if (!require("forecast")) install.packages("forecast")
library(forecast)
alpha=0.1
I$lissage_expo_simple=ses(I$sum,alpha=alpha,initial = "simple")$fitted

ggplot(I,aes(x=day,y=sum)) +
geom_point() +
geom_line(aes(y=lissage_expo_simple),col="red",size=1) #lissage expo en courbe avec ligne 

#modèle peut adapter selon moi car les données sont trop chaotiques


ggplot(I, aes(x=I$day,y=I$lissage_expo_simple))+
         geom_point()
#doublé
I$lissage_expo_double=ses(I$lissage_expo_simple,alpha = alpha,initial="simple")$fitted

#modele pre 2017 => prevision vs modele post 2017

#saisonnalité de 7 jours ?
plot(y=I$sum,x=I$day,xlim = c(as.Date("2016-01-01"),as.Date("2016-02-01")))
 p=list()
for (i in seq(1,length(I$sum),by=7)){
  p[i]=I$sum[i]
  
}
#remove NULL
p <- Filter(Negate(is.null), p)
p
plot(y=p,x=1:length(p))
```

```{r}
library(ggplot2)
library(zoo)

# Créez un dataframe I avec des colonnes "day" et "sum"
# Remplacez cela par votre propre dataframe si nécessaire

# Créez une plage de valeurs pour k de 1 à 20
k_values <- 1:20

# Créez une liste vide pour stocker les graphiques ggplot
plots <- list()

# Boucle sur les différentes valeurs de k
for (k in k_values) {
  # Calculer la moyenne mobile avec rollmean
  I$mm <- c(rep(NA, k), zoo::rollmean(I$sum, k = 2 * k + 1), rep(NA, k))
  
  # Créer le graphique ggplot
  p <- ggplot(I, aes(x = day, y = mm)) +
    geom_point() +
    labs(title = paste("k =", k), x = "Date", y = "Moyenne mobile")
  
  # Ajouter le graphique à la liste
  plots[[k]] <- p
}
print(plots)


```

